### ISSUE TITLE
ZT582KL RAW Incomplete unpacking

### ISSUE THREAD

**Issue by weijen6** [Yoti/unraw#1]
https://firmwarefile.com/asus-zenpad-z8s-zt582kl

I use 7-zip to view raw files, There are 44 files in total.
But using unraw to unpack, only get 16 files.
And I use the hex editor to view boot.img, the file content is not correct..

**Comment by Yoti** [comment]
This RAW has 16 files inside. RAW size is 3.33GB, all files size are 3.33GB. Do not use 7-Zip.
```
C:\Users\Yoti\Downloads>unraw.exe ZT582KL_all_VZW_user_V3.5.2.raw
Asus RAW unpacker by Yoti
Src: ZT582KL_all_VZW_user_V3.5.2.raw
Mode: v2
Count: 16 <-- THIS
gpt_both0.bin (34304)
rpm.mbn (167200)
hyp.mbn (73728)
quality.img (4513940)
keymaster.mbn (226008)
recovery.img (40946928)
cmnlib.mbn (197184)
sbl1.mbn (361832)
tz.mbn (1375488)
NON-HLOS.bin (84105728)
asdf.img (33554432)
adspso.bin (16777216)
emmc_appsboot.signed.mbn (1201416)
devcfg.mbn (33468)
system.img (3368996936)
boot.img (33643756)
Dst: ZT582KL_all_VZW_user_V3.5.2\
The job was done with success <-- THIS
```

**Comment by weijen6** [comment]
Thank you for your reply, Another problem is that the boot.img is incorrect
The file header of boot.img should be ANDROID
![image](https://user-images.githubusercontent.com/32688959/114272491-f85b7c00-9a48-11eb-9e97-a63323d34917.png)
![image](https://user-images.githubusercontent.com/32688959/114272565-4d978d80-9a49-11eb-83c6-7bac20d2e5c9.png)

**Comment by Yoti** [comment]
Yep, this is a bug.

**Comment by Yoti** [comment]
Fixed in https://github.com/Yoti/unraw/commit/78cff467cc52a0e83fdae47a455a3dce2a27e405

Release: https://github.com/Yoti/unraw/releases/tag/v1.1
